# Generated by Django 5.2.6 on 2025-09-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
