# Generated by Django 5.2.6 on 2025-09-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roll', '0002_session_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='anon_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
